//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BottomToolbar) DeepCopyInto(out *BottomToolbar) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BottomToolbar.
func (in *BottomToolbar) DeepCopy() *BottomToolbar {
	if in == nil {
		return nil
	}
	out := new(BottomToolbar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BottomToolbar) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BottomToolbarList) DeepCopyInto(out *BottomToolbarList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BottomToolbar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BottomToolbarList.
func (in *BottomToolbarList) DeepCopy() *BottomToolbarList {
	if in == nil {
		return nil
	}
	out := new(BottomToolbarList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BottomToolbarList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BottomToolbarSpec) DeepCopyInto(out *BottomToolbarSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BottomToolbarSpec.
func (in *BottomToolbarSpec) DeepCopy() *BottomToolbarSpec {
	if in == nil {
		return nil
	}
	out := new(BottomToolbarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BottomToolbarStatus) DeepCopyInto(out *BottomToolbarStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BottomToolbarStatus.
func (in *BottomToolbarStatus) DeepCopy() *BottomToolbarStatus {
	if in == nil {
		return nil
	}
	out := new(BottomToolbarStatus)
	in.DeepCopyInto(out)
	return out
}
